### PR TITLE
Update Coq proof to make it forward compatible with newer versions of Coq

### PR DESCRIPTION
**Pull request by roconnor-blockstream**
Tested with Coq 8.17.1.

### CODE REVIEW

**Comment by sipa** [comment]
~~What commands would I run to test this?~~

EDIT: oh, there is a README. Running.

**Comment by roconnor-blockstream** [comment]
See you back here in a few days. :)

**Comment by roconnor-blockstream** [comment]
If you are impatient, you can "cheat" by replacing `Time Qed.` with `Admitted.` in the `coq/divstep/divsteps724.v` and `coq/hddivesteps/hddivsteps590.v` files, and they will compile quickly, bypassing the hard check.  Or you can just let them run for a day or two.  I'm in no particular rush.

**Comment by sipa** [comment]
```
$ coqc --version
The Coq Proof Assistant, version 8.18.0
compiled with OCaml 4.14.1
```

```
divsteps724_gcd
     : forall f g : Z,
       Z.Odd f ->
       (f <=
        117158902872583173497613320875115869681332052015104310001724282359164641678770)%Z ->
       (0 <= g <= f)%Z ->
       Znumtheory.Zis_gcd f g
         (divsteps.f (N.iter 724 divsteps.step (divsteps.init f g)))
Closed under the global context
divsteps724_inverse
     : forall f g : Z,
       Z.Odd f ->
       (f <=
        117158902872583173497613320875115869681332052015104310001724282359164641678770)%Z ->
       (0 <= g <= f)%Z ->
       Znumtheory.rel_prime f g ->
       let st := N.iter 724 divsteps.step (divsteps.init f g) in
       Z.abs (divsteps.f st) = 1%Z /\
       eqm f (divsteps.d st * divsteps.f st * g) 1
Closed under the global context
divsteps724_prime_inverse
     : forall f g : Z,
       Z.Odd f ->
       Znumtheory.prime f ->
       (g < f <=
        117158902872583173497613320875115869681332052015104310001724282359164641678770)%Z ->
       let st := N.iter 724 divsteps.step (divsteps.init f g) in
       (g = 0%Z -> divsteps.d st = 0%Z) /\
       ((0 < g)%Z ->
        Z.abs (divsteps.f st) = 1%Z /\
        eqm f (divsteps.d st * divsteps.f st * g) 1)
Closed under the global context

real    1600m33.179s
user    1599m6.172s
sys     0m3.425s
```

**Comment by sipa** [comment]
ACK 06996a3bca84cfddddf4fdd68778831d77e30e7f

**Comment by roconnor-blockstream** [comment]
Technically you will also want to do the same check in the hddivsteps directory.

**Comment by sipa** [comment]
I did, in parallel with the other one. I didn't save the output, but it was successful.

**Pull request merged**
